In [ ]:
import numpy as np
import tensorflow #open source used for both ML and DL for computation
from tensorflow.keras.datasets import mnist #mnist dataset
from tensorflow.keras.models import Sequential #it is a plain stack of layers
from tensorflow.keras import layers #A Layer consists of a tensor- in tensor-out computat ion funct ion
from tensorflow.keras.layers import Dense, Flatten #Dense-Dense Layer is the regular deeply connected r
#faltten -used fot flattening the input or change the dimension
from tensorflow.keras.layers import Conv2D #onvoLutiona l Layer
from keras.optimizers import Adam #opt imizer
from keras. utils import np_utils #used for one-hot encoding
import matplotlib.pyplot as plt   #used for data visualization

Load the Data

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

Data Pre-Processing 

In [ ]:
X_train=X_train.reshape (60000, 28, 28, 1).astype('float32')
X_test=X_test.reshape (10000, 28, 28, 1).astype ('float32')
number_of_classes = 10
Y_train = np_utils.to_categorical(y_train, number_of_classes)
Y_test = np_utils.to_categorical(y_test, number_of_classes)

In [ ]:
Y_train[888]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

Add CNN Layer

In [ ]:
#Create the Model
model=Sequential ()

In [ ]:
#adding modeL Layer
model.add(Conv2D(64, (3, 3), input_shape=(28, 28, 1), activation='relu'))
model.add(Conv2D(32, (3, 3), activation = 'relu'))

In [ ]:
#flatten the dimension of the image
model.add(Flatten())
#output layer with 10 neurons
model.add(Dense(number_of_classes,activation = 'softmax'))

 
 
 
 
 
 
 
 
 
Compiling The Model

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=["accuracy"])

In [ ]:
model.fit(X_train, Y_train, batch_size=32, epochs=5, validation_data=(X_test,Y_test))

Epoch 1/5
1875/1875 [==============================] - 193s 102ms/step - loss: 0.2747 - accuracy: 0.9462 - val_loss: 0.1106 - val_accuracy: 0.9663
Epoch 2/5
1875/1875 [==============================] - 192s 102ms/step - loss: 0.0763 - accuracy: 0.9770 - val_loss: 0.0830 - val_accuracy: 0.9732
Epoch 3/5
1875/1875 [==============================] - 193s 103ms/step - loss: 0.0533 - accuracy: 0.9833 - val_loss: 0.1066 - val_accuracy: 0.9691
Epoch 4/5
1875/1875 [==============================] - 192s 103ms/step - loss: 0.0404 - accuracy: 0.9876 - val_loss: 0.0918 - val_accuracy: 0.9737
Epoch 5/5
1875/1875 [==============================] - 193s 103ms/step - loss: 0.0333 - accuracy: 0.9894 - val_loss: 0.1098 - val_accuracy: 0.9733


Test the Model

In [ ]:
metrics = model.evaluate(X_test, Y_test, verbose=0)
print("Metrics (Test Loss & Test Accuracy): ")
print(metrics)

Metrics (Test Loss & Test Accuracy): 
[0.1098330095410347, 0.9732999801635742]


In [ ]:
prediction=model.predict(X_test[6000:6007])
print(prediction)

1/1 [==============================] - 0s 26ms/step
[[5.8028406e-16 6.0908377e-18 5.3280164e-15 1.7032078e-09 1.5333529e-07
  2.5937838e-10 7.3504640e-16 2.0802499e-06 4.4689141e-09 9.9999774e-01]
 [4.6930425e-03 2.6736107e-06 5.1415685e-05 2.8996649e-06 3.6830591e-11
  1.5965476e-05 5.1742398e-07 2.9544536e-10 9.9510264e-01 1.3079790e-04]
 [1.2195903e-10 8.2684917e-09 1.4382446e-12 4.1655465e-10 5.1632537e-07
  1.4045388e-07 9.9999940e-01 2.0163050e-15 4.1881766e-08 7.5915203e-12]
 [9.9995303e-01 2.1252743e-12 3.9191577e-06 2.0184658e-08 3.3402857e-13
  1.9101368e-07 2.9537131e-09 8.5483351e-13 5.6683834e-06 3.7114671e-05]
 [1.1165393e-07 3.0429690e-11 5.8592873e-09 1.1337650e-04 6.3033062e-06
  2.3419200e-03 4.1620038e-05 6.1424394e-08 1.0467838e-01 8.9281815e-01]
 [5.5297202e-21 1.0000000e+00 2.1706649e-12 6.8361359e-14 2.8971048e-10
  1.7955520e-10 2.1375397e-14 3.2710622e-17 1.6486626e-10 7.8509945e-19]
 [2.5148014e-11 8.9673289e-05 1.7767622e-08 3.0850337e-05 3.9560572e-08
  2.86

In [ ]:
print(numpy.argmax(prediction, axis=1))
print(Y_test[:4])

[9 8 6 0 9 1 7]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Save the Model

In [ ]:
model.save('models/mnistCNN.h5')